# Source Repo for Shadow POC
# Dest Repo is https://github.com/Grax32/NodeDice.git

parameters:
- name: githubRepo
  displayName: GitHub Repo (without the https)
  type: string

- name: userName
  displayName: GitHub User Name
  type: string

- name: token
  displayName: GitHub Token
  type: string

- name: branch
  displayName: GitHub Branch
  type: string
  default: dev

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: git push https://${{ parameters.userName }}:${{ parameters.token }}@${{ parameters.githubRepo }} HEAD:${{ parameters.branch }}
  displayName: Push to GitHub
