# Source Repo for Shadow POC
# Dest Repo is https://github.com/Grax32/NodeDice.git

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo 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 | gh auth login --with-token
  displayName: 'GitHub Authentication'

- script: git push https://github.com/Grax32/NodeDice.git HEAD:dev
  displayName: Push to GitHub
