# Source Repo for Shadow POC
# Dest Repo is https://github.com/Grax32/NodeDice.git

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: git status
  displayName: 'Status'

- script: |
    echo Git Log
    git log
  displayName: 'History'

- script: git push https://github.com/Grax32/NodeDice.git HEAD:dev
  displayName: Push to GitHub
